export const DATA__FETCH_DATA_PENDING = 'DATA__FETCH_DATA_PENDING';
export const DATA__FETCH_DATA_SUCCESS = 'DATA__FETCH_DATA_SUCCESS';
export const DATA__FETCH_DATA_ERROR = 'DATA__FETCH_DATA_ERROR';
export const DATA__UPDATE_DATA = 'DATA__UPDATE_DATA';
